# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=/Users/mac/Library/Java/JavaVirtualMachines/jdk-17.0.11+9/Contents/Home
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true
# Multidex is usually handled by multiDexEnabled in build.gradle, but these are good to have
android.nonTransitiveRClass=true
